# Generated by Django 4.2.4 on 2023-08-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(max_length=15)),
                ('to_number', models.CharField(max_length=15)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
